// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odsxkpqynbimgcdixupc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kc3hrcHF5bmJpbWdjZGl4dXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTYzODcsImV4cCI6MjA2NzEzMjM4N30.4c_5XQwUh08g0Pb9Umie7976d2Pp0y_dIcbUwKkE2Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});